apiVersion: v1
data:
  nr-ue.conf: "uicc0 = {\n  imsi = \"999700000000002\";\n  key = \"465B5CE8B199B49FAA5F0A2EE238A6BC\"\
    ;\n  opc = \"E8ED289DEBA952E4283B54E88E6183CA\";\n  dnn = \"oai\";\n  nssai_sst\
    \ = 1;\n  nssai_sd = 0xffffff;\n}\n\nposition0 = {\n    x = 0.0;\n    y = 0.0;\n\
    \    z = 6377900.0;\n}\n\nthread-pool = \"-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1\"\
    \n\nrfsimulator = (\n  {\n    serveraddr = \"server\";\n  }\n);\n\nchannelmod\
    \ = {\n  max_chan = 10;\n  modellist = \"modellist_rfsimu_1\";\n  modellist_rfsimu_1\
    \ = (\n    {\n      model_name     = \"rfsimu_channel_enB0\"\n      type     \
    \      = \"AWGN\";\n      ploss_dB       = 20;\n      noise_power_dB = -4;\n \
    \     forgetfact     = 0;\n      offset         = 0;\n      ds_tdl         = 0;\n\
    \    },\n    {\n      model_name     = \"rfsimu_channel_ue0\"\n      type    \
    \       = \"AWGN\";\n      ploss_dB       = 20;\n      noise_power_dB = -2;\n\
    \      forgetfact     = 0;\n      offset         = 0;\n      ds_tdl         =\
    \ 0;\n    }\n  );\n};\n"
kind: ConfigMap
metadata:
  name: oai-nrue-config-2
  namespace: oran-ran

