apiVersion: v1
data:
  nr-ue.conf: |
    uicc0 = {
      imsi = "999700000000004";
      key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
      opc = "E8ED289DEBA952E4283B54E88E6183CA";
      pdu_sessions = ({ dnn = "oai"; nssai_sst = 1; nssai_sd = 0xffffff; });
    }

    position0 = {
        x = 0.0;
        y = 0.0;
        z = 6377900.0;
    }

    thread-pool = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

    rfsimulator = (
      {
        serveraddr = "oai-du1-rfsim";
      }
    );

    channelmod = {
      max_chan = 10;
      modellist = "modellist_rfsimu_1";
      modellist_rfsimu_1 = (
        {
          model_name     = "rfsimu_channel_enB0"
          type           = "AWGN";
          ploss_dB       = 20;
          noise_power_dB = -4;
          forgetfact     = 0;
          offset         = 0;
          ds_tdl         = 0;
        },
        {
          model_name     = "rfsimu_channel_ue0"
          type           = "AWGN";
          ploss_dB       = 20;
          noise_power_dB = -2;
          forgetfact     = 0;
          offset         = 0;
          ds_tdl         = 0;
        }
      );
    };
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nr-ue.conf":"uicc0 = {\n  imsi = \"999700000000004\";\n  key = \"465B5CE8B199B49FAA5F0A2EE238A6BC\";\n  opc = \"E8ED289DEBA952E4283B54E88E6183CA\";\n  pdu_sessions = ({ dnn = \"oai\"; nssai_sst = 1; nssai_sd = 0xffffff; });\n}\n\nposition0 = {\n    x = 0.0;\n    y = 0.0;\n    z = 6377900.0;\n}\n\nthread-pool = \"-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1\"\n\nrfsimulator = (\n  {\n    serveraddr = \"server\";\n  }\n);\n\nchannelmod = {\n  max_chan = 10;\n  modellist = \"modellist_rfsimu_1\";\n  modellist_rfsimu_1 = (\n    {\n      model_name     = \"rfsimu_channel_enB0\"\n      type           = \"AWGN\";\n      ploss_dB       = 20;\n      noise_power_dB = -4;\n      forgetfact     = 0;\n      offset         = 0;\n      ds_tdl         = 0;\n    },\n    {\n      model_name     = \"rfsimu_channel_ue0\"\n      type           = \"AWGN\";\n      ploss_dB       = 20;\n      noise_power_dB = -2;\n      forgetfact     = 0;\n      offset         = 0;\n      ds_tdl         = 0;\n    }\n  );\n};\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"oai-nrue-config-4","namespace":"oran-ran"}}
  creationTimestamp: "2026-05-07T09:11:18Z"
  name: oai-nrue-config-4
  namespace: oran-ran
  resourceVersion: "453466"
  uid: 36fd156d-443e-4cea-bd50-ea44a943f0e2
