apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-cu
  namespace: oran-ran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-cu
  template:
    metadata:
      labels:
        app: oai-cu
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"n2-net","ips":["10.10.0.120/24"]},{"name":"n3-net","ips":["10.20.0.120/24"]}]'
    spec:
      containers:
      - name: oai-cu
        image: oaisoftwarealliance/oai-gnb:2025.w45
        imagePullPolicy: IfNotPresent
        command: ["/opt/oai-gnb/bin/nr-softmodem"]
        args:
          - "-O"
          - "/opt/oai-gnb/etc/gnb.conf"
          - "--log_config.global_log_options"
          - "level,nocolor,time"
          - "--telnetsrv"
          - "--telnetsrv.shrmod"
          - "ci"
        securityContext:
          capabilities:
            add: ["SYS_NICE"]
        volumeMounts:
        - name: cu-config
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      volumes:
      - name: cu-config
        configMap:
          name: oai-cu-f1-config
---
apiVersion: v1
kind: Service
metadata:
  name: oai-cu-ci
  namespace: oran-ran
spec:
  selector:
    app: oai-cu
  ports:
  - name: ci
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-du0
  namespace: oran-ran
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oai-du0
  template:
    metadata:
      labels:
        app: oai-du0
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"n2-net","ips":["10.10.0.121/24"]}]'
    spec:
      containers:
      - name: oai-du0
        image: oaisoftwarealliance/oai-gnb:2025.w45
        imagePullPolicy: IfNotPresent
        command: ["/opt/oai-gnb/bin/nr-softmodem"]
        args:
          - "-O"
          - "/opt/oai-gnb/etc/gnb.conf"
          - "-E"
          - "--rfsim"
          - "--rfsimulator.serveraddr"
          - "oai-nr-ue-f1-rfsim"
          - "--rfsimulator.serverport"
          - "4043"
          - "--log_config.global_log_options"
          - "level,nocolor,time"
        securityContext:
          capabilities:
            add: ["SYS_NICE"]
        volumeMounts:
        - name: du-config
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      volumes:
      - name: du-config
        configMap:
          name: oai-du0-f1-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-du1
  namespace: oran-ran
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oai-du1
  template:
    metadata:
      labels:
        app: oai-du1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"n2-net","ips":["10.10.0.132/24"]}]'
    spec:
      containers:
      - name: oai-du1
        image: oaisoftwarealliance/oai-gnb:2025.w45
        imagePullPolicy: IfNotPresent
        command: ["/opt/oai-gnb/bin/nr-softmodem"]
        args:
          - "-O"
          - "/opt/oai-gnb/etc/gnb.conf"
          - "-E"
          - "--rfsim"
          - "--rfsimulator.serveraddr"
          - "oai-nr-ue-f1-rfsim"
          - "--rfsimulator.serverport"
          - "4043"
          - "--log_config.global_log_options"
          - "level,nocolor,time"
        securityContext:
          capabilities:
            add: ["SYS_NICE"]
        volumeMounts:
        - name: du-config
          mountPath: /opt/oai-gnb/etc/gnb.conf
          subPath: gnb.conf
      volumes:
      - name: du-config
        configMap:
          name: oai-du1-f1-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-nrue-f1-config
  namespace: oran-ran
data:
  nr-ue.conf: |
    uicc0 = {
      imsi = "999700000000006";
      key = "465B5CE8B199B49FAA5F0A2EE238A6BC";
      opc = "E8ED289DEBA952E4283B54E88E6183CA";
      pdu_sessions = ({ dnn = "oai"; nssai_sst = 1; nssai_sd = 0xffffff; });
    }

    position0 = {
        x = 0.0;
        y = 0.0;
        z = 6377900.0;
    }

    thread-pool = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

    rfsimulator = (
      {
        serveraddr = "server";
      }
    );

    channelmod = {
      max_chan = 10;
      modellist = "modellist_rfsimu_1";
      modellist_rfsimu_1 = (
        {
          model_name     = "rfsimu_channel_enB0"
          type           = "AWGN";
          ploss_dB       = 20;
          noise_power_dB = -4;
          forgetfact     = 0;
          offset         = 0;
          ds_tdl         = 0;
        },
        {
          model_name     = "rfsimu_channel_ue0"
          type           = "AWGN";
          ploss_dB       = 20;
          noise_power_dB = -2;
          forgetfact     = 0;
          offset         = 0;
          ds_tdl         = 0;
        }
      );
    };
---
apiVersion: v1
kind: Service
metadata:
  name: oai-nr-ue-f1-rfsim
  namespace: oran-ran
spec:
  selector:
    app: oai-nr-ue-f1
  ports:
  - name: rfsim
    port: 4043
    targetPort: 4043
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nr-ue-f1
  namespace: oran-ran
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oai-nr-ue-f1
  template:
    metadata:
      labels:
        app: oai-nr-ue-f1
    spec:
      containers:
      - name: oai-nr-ue-f1
        image: oaisoftwarealliance/oai-nr-ue:2025.w45
        imagePullPolicy: IfNotPresent
        command:
        - /opt/oai-nr-ue/bin/nr-uesoftmodem
        args:
        - "-O"
        - "/opt/oai-nr-ue/etc/nr-ue.conf"
        - "-E"
        - "--rfsim"
        - "-r"
        - "106"
        - "--numerology"
        - "1"
        - "-C"
        - "3450720000"
        - "--ssb"
        - "516"
        - "--rfsimulator.serveraddr"
        - "server"
        - "--rfsimulator.serverport"
        - "4043"
        - "--log_config.global_log_options"
        - "level,nocolor,time"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_NICE
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /opt/oai-nr-ue/etc/nr-ue.conf
          name: nrue-f1-config
          subPath: nr-ue.conf
        - mountPath: /dev/net/tun
          name: tun-device
      volumes:
      - name: nrue-f1-config
        configMap:
          name: oai-nrue-f1-config
      - name: tun-device
        hostPath:
          path: /dev/net/tun
          type: CharDevice
