apiVersion: v1
kind: Service
metadata:
  name: oai-nr-ue-rfsim
  namespace: oran-ran
spec:
  selector:
    app: oai-nr-ue
  ports:
  - name: rfsim
    protocol: TCP
    port: 4043
    targetPort: 4043
