apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"oai-nr-ue-rfsim","namespace":"oran-ran"},"spec":{"ports":[{"name":"rfsim","port":4043,"protocol":"TCP","targetPort":4043}],"selector":{"app":"oai-nr-ue"}}}
  creationTimestamp: "2026-03-16T15:07:44Z"
  name: oai-nr-ue-rfsim
  namespace: oran-ran
  resourceVersion: "46072"
  uid: 71839508-3f54-4fd0-905c-30efffa419db
spec:
  clusterIP: 10.43.44.158
  clusterIPs:
  - 10.43.44.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rfsim
    port: 4043
    protocol: TCP
    targetPort: 4043
  selector:
    app: oai-nr-ue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
