network:
  version: 2
  renderer: NetworkManager
  bridges:
    br-n2:
      addresses: [10.10.0.1/24]
      dhcp4: no
      parameters:
        stp: false
        forward-delay: 0
    br-n3:
      addresses: [10.20.0.1/24]
      dhcp4: no
      parameters:
        stp: false
        forward-delay: 0
